Mox.defmock(Screenplay.RoutePatterns.Mock, for: Screenplay.RoutePatterns.Behaviour)
Mox.defmock(Screenplay.Stops.Mock, for: Screenplay.Stops.Stop)
Mox.defmock(Screenplay.Routes.Mock, for: Screenplay.Routes.Route)
Mox.defmock(Screenplay.Facilities.Mock, for: Screenplay.Facilities.Facility)
Mox.defmock(HTTPoison.Mock, for: HTTPoison.Base)
