name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev
        options:
        - dev
        - dev-blue
        - dev-green
  push:
    branches: [main]

permissions: {}

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@ba8d62bff3a4aa0df22eb2d6a1ce7ad4fb2eac1a # v5.1.1
    with:
      app-name: screenplay
      environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
